#!/bin/sh -e
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

###############################################################################
# Use the -e option so the script will fail on the first non-zero return code.

# This is a script to tag all the repos when a fix is generated. Since
# generally only about 1 repo gets touched for a fix, it will save time
# to automate the tagging of the rest of them. This script assumes that
# all the repos have the fix checked in, and are in the desired state
# (because you would already be in the desired state immediately after 
# testing your fix). It will do a "git checkout" of the specified branch.

if [ "$1" = "" ]
then
    echo "Loading the settings from corimf-settings..."
    source corimf-settings
else
    echo "Loading the settings from $1"
    source "$1"
fi

echo "REMOTE_ORIGIN=$REMOTE_ORIGIN"
echo "BRANCH=$BRANCH"
echo "NEW_TAG=$NEW_TAG"

/bin/echo -n "Hit ENTER to continue: "
read ANSWER

# Shouldn't need to change anything below here.

check_rc() {
    SAVE_RC=$?
    if [ $SAVE_RC != 0 ]
    then
        echo "Failed."
        exit $RC
    elif [ "$DONE" = 1 ]
    then
        echo "Success."
    else
        echo "Incomplete."
        exit 1
    fi
}

trap check_rc EXIT

echo "Checking that we are one dir above the git repo..."
test -d $PLATFORM_REPO

echo "Checking major version number..."
MAJOR=`echo $BRANCH | cut -f1 -d.`
test "$MAJOR" -ge 2 -a "$MAJOR" -le 3

if [ "$MAJOR" -ge 3 ]
then
    echo "Checking that the plugin count is $PLUGIN_COUNT..."
    COUNT=0
    for PLUGIN in $PLUGINS
    do
        COUNT=`expr $COUNT + 1`
    done
    test "$COUNT" == "$PLUGIN_COUNT"
else
    echo "Skipping all plugins since version is $MAJOR"
    PLUGINS=
    PLUGMAN_REPO=
    PLATFORM_REPOS="cordova-android cordova-ios cordova-windows cordova-wp8 cordova-blackberry cordova-js"
    OTHER_REPOS=
fi

echo "Checking that each repo exists..."
for DIR in $PLATFORM_REPOS $PLUGINS $OTHER_REPOS
do
    test -d $DIR
done

echo "Checking that $REMOTE_ORIGIN is a defined remote..."
for DIR in $PLATFORM_REPOS $PLUGINS $OTHER_REPOS
do
    pushd $DIR
    git remote | grep $REMOTE_ORIGIN
    popd
done

echo "Checking out $BRANCH for platforms and plugins and others..."
for DIR in $PLATFORM_REPOS $PLUGINS $OTHER_REPOS
do
    pushd $DIR
    git checkout $BRANCH || git checkout -b $BRANCH $REMOTE_ORIGIN/$BRANCH
    git pull $REMOTE_ORIGIN $BRANCH
    git fetch --tags $REMOTE_ORIGIN
    popd
done

echo "Tagging the end of $BRANCH for platforms and plugins and others..."
for DIR in $PLATFORM_REPOS $PLUGINS $OTHER_REPOS
do
    pushd $DIR
    # check to see if the tag already exists
    EXISTS=`git tag | grep "$NEW_TAG"` || true
    if [ -z "$EXISTS" ]
    then
        echo "Creating tag $NEW_TAG"
        git tag $NEW_TAG
        git push $REMOTE_ORIGIN $NEW_TAG
    else
        # make sure the tag is at the end of the branch
        EXPECTED=`git rev-parse $BRANCH`
        ACTUAL=`git rev-parse $NEW_TAG`
        if [ "$EXPECTED" = "$ACTUAL" ]
        then
            echo "Tag $NEW_TAG already exists for $DIR. Looks to be OK."
        else
            # fail with an error
            echo "For $DIR tag $NEW_TAG already exists with $ACTUAL but is expected to to $EXPECTED"
            false
        fi
    fi
    popd
done

DONE=1
