#!/bin/sh -e
#
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

##############################################################################
# This is a script to show the versions of all the plugins. This is only for
# display, it does not do any checking/verification to see if the plugin
# version is correct. The intent is to manually compare this to the blog post
# on cordova.apache.org that it is as expected.

if [ "$1" = "" ]
then
    echo "Loading the settings from corimf-settings..."
    source corimf-settings
else
    echo "Loading the settings from $1"
    source "$1"
fi

echo "NEW_TAG=$NEW_TAG"

/bin/echo -n "Hit ENTER to continue: "
read ANSWER

check_rc() {
    SAVE_RC=$?
    if [ $SAVE_RC != 0 ]
    then
        echo "Failed."
        exit $RC
    elif [ "$DONE" = 1 ]
    then
        echo "Success."
    else
        echo "Incomplete."
        exit 1
    fi
}

trap check_rc EXIT

TEMPFILENAME=$(mktemp tmp-showver-XXXXXX)
test ! -z "$TEMPFILENAME"

echo "Displaying plugin versions (from plugin.xml) from repo at $NEW_TAG:"

for DIR in $PLUGINS
do
    /bin/echo -n "$DIR: "
    test -d $DIR
    cd $DIR
    # check that tag exists, or else the whole script stops
    EXISTS=`git tag | grep "$NEW_TAG"` || true
    if [ -z "$EXISTS" ]
    then
        echo "WARNING: No tag $NEW_TAG for $DIR"
        continue
    fi
    git show $NEW_TAG:plugin.xml > $TEMPFILENAME
    xmllint --shell $TEMPFILENAME << EOD | grep content | cut -f2 -d=
setns defns=http://apache.org/cordova/ns/plugins/1.0
xpath /defns:plugin/@version
EOD
    rm $TEMPFILENAME
    cd ..
done

DONE=1
